// <auto-generated />
using System;
using CoopagcuyApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoopagcuyApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705192505_SyncIdempotenciaEntregas")]
    partial class SyncIdempotenciaEntregas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoopagcuyApi.Common.Auth.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CatAsignado")
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Catalogos.Models.Comunidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CatReferencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Comunidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Canton = "Pucará",
                            CatReferencia = "PAT",
                            Nombre = "Patococha"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Canton = "Nabón",
                            CatReferencia = "NIE",
                            Nombre = "Las Nieves"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Canton = "Santa Isabel",
                            CatReferencia = "HUE",
                            Nombre = "Huertas"
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Canton = "Nabón",
                            CatReferencia = "NAB",
                            Nombre = "Nabón / El Progreso"
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Canton = "Pucará",
                            CatReferencia = "PEL",
                            Nombre = "Pelincay"
                        });
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.CuyFaenamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("NumeroEnLote")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PesoCanalGramos")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("RegistroFaenamientoId")
                        .HasColumnType("integer");

                    b.Property<bool>("RetornadoAProductora")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RegistroFaenamientoId", "NumeroEnLote")
                        .IsUnique();

                    b.ToTable("CuyFaenamientos");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.Despacho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadUnidades")
                        .HasColumnType("integer");

                    b.Property<string>("ClienteDestino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaDespacho")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transporte")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Despachos");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.Devolucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadUnidades")
                        .HasColumnType("integer");

                    b.Property<string>("ClienteDevuelve")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("RegistroFaenamientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("RegistroFaenamientoId");

                    b.ToTable("Devoluciones");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.LoteFaenado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaFaenamiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OperarioResponsable")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("TemperaturaAlmacenamiento")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("LotesFaenados");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.RegistroFaenamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoCanal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFaenamiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaIngresoFrio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaSalidaFrio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LoteFaenadoId")
                        .HasColumnType("integer");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoDecomiso")
                        .HasColumnType("text");

                    b.Property<int>("NumeroSesion")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("OperarioResponsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PesoTotalCanalGramos")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("PresentacionEmpaque")
                        .HasColumnType("text");

                    b.Property<decimal?>("TemperaturaAlmacenamiento")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int?>("TiempoLavadoMinutos")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadesDecomisadas")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadesFaenadas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoteFaenadoId");

                    b.HasIndex("LoteId");

                    b.ToTable("Faenamientos");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.RetornoProductora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaRetorno")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("NumeroEnLote")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoraId")
                        .HasColumnType("integer");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("ProductoraId");

                    b.ToTable("RetornosProductora");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Productoras.Models.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadAnimales")
                        .HasColumnType("integer");

                    b.Property<string>("CentroAcopio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Cerrado")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoLote")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("PesoTotalGramos")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("ProductoraId")
                        .HasColumnType("integer");

                    b.Property<string>("ResponsableRecepcion")
                        .HasColumnType("text");

                    b.Property<string>("SignosClinicos")
                        .HasColumnType("text");

                    b.Property<bool>("SincronizadoOffline")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CodigoLote")
                        .IsUnique();

                    b.HasIndex("ProductoraId");

                    b.HasIndex("CentroAcopio", "Cerrado");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Productoras.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LoteId")
                        .HasColumnType("integer");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("MontoUsd")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProductoraId")
                        .HasColumnType("integer");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("ProductoraId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Productoras.Models.Productora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CatAsignado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Comunidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Productoras");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Productoras.Models.ProductoraCambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CampoModificado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ProductoraId")
                        .HasColumnType("integer");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ValorNuevo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoraId");

                    b.ToTable("ProductoraCambios");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.QR.Models.CodigoQR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("BlobPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LoteFaenadoId")
                        .HasColumnType("integer");

                    b.Property<int?>("LoteId")
                        .HasColumnType("integer");

                    b.Property<string>("UrlPublica")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("LoteFaenadoId");

                    b.HasIndex("LoteId")
                        .IsUnique();

                    b.ToTable("CodigosQR");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Recepcion.Models.CuyRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorPelaje")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoOreja")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoNovedad")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("NumeroEnLote")
                        .HasColumnType("integer");

                    b.Property<decimal>("PesoGramos")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("ProductoraId")
                        .HasColumnType("integer");

                    b.Property<string>("SignosClinicos")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TamanoAnimal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoraId");

                    b.HasIndex("LoteId", "NumeroEnLote")
                        .IsUnique();

                    b.ToTable("CuyRegistros");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Recepcion.Models.Movilizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadMovilizada")
                        .HasColumnType("integer");

                    b.Property<string>("CondicionLlegada")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CondicionesTransporte")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Conductor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("DiasRetiroMedicamentos")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaDespacho")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaRecepcionPlanta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RecibidoPor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ResponsableDespacho")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TipoForraje")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LoteId")
                        .IsUnique();

                    b.ToTable("Movilizaciones");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Recepcion.Models.Novedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PesoRegistradoGramos")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("RegistradoPor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Novedades");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Recepcion.Models.SyncEntregaProcesada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DispositivoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaProcesado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IdCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId", "IdCliente")
                        .IsUnique();

                    b.ToTable("SyncEntregasProcesadas");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.CuyFaenamiento", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Faenamiento.Models.RegistroFaenamiento", "Registro")
                        .WithMany("Cuyes")
                        .HasForeignKey("RegistroFaenamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.Despacho", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.Devolucion", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoopagcuyApi.Features.Faenamiento.Models.RegistroFaenamiento", "RegistroFaenamiento")
                        .WithMany()
                        .HasForeignKey("RegistroFaenamientoId");

                    b.Navigation("Lote");

                    b.Navigation("RegistroFaenamiento");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.RegistroFaenamiento", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Faenamiento.Models.LoteFaenado", "LoteFaenado")
                        .WithMany("Sesiones")
                        .HasForeignKey("LoteFaenadoId");

                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Lote", "Lote")
                        .WithMany("Faenamientos")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("LoteFaenado");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.RetornoProductora", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Productora", "Productora")
                        .WithMany()
                        .HasForeignKey("ProductoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("Productora");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Productoras.Models.Lote", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Productora", "Productora")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoraId");

                    b.Navigation("Productora");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Productoras.Models.Pago", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId");

                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Productora", "Productora")
                        .WithMany()
                        .HasForeignKey("ProductoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("Productora");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Productoras.Models.ProductoraCambio", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Productora", "Productora")
                        .WithMany()
                        .HasForeignKey("ProductoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Productora");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.QR.Models.CodigoQR", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Faenamiento.Models.LoteFaenado", "LoteFaenado")
                        .WithMany()
                        .HasForeignKey("LoteFaenadoId");

                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Lote", "Lote")
                        .WithOne("CodigoQR")
                        .HasForeignKey("CoopagcuyApi.Features.QR.Models.CodigoQR", "LoteId");

                    b.Navigation("Lote");

                    b.Navigation("LoteFaenado");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Recepcion.Models.CuyRegistro", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Lote", "Lote")
                        .WithMany("Cuyes")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Productora", "Productora")
                        .WithMany()
                        .HasForeignKey("ProductoraId");

                    b.Navigation("Lote");

                    b.Navigation("Productora");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Recepcion.Models.Movilizacion", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Lote", "Lote")
                        .WithOne("Movilizacion")
                        .HasForeignKey("CoopagcuyApi.Features.Recepcion.Models.Movilizacion", "LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Recepcion.Models.Novedad", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Lote", "Lote")
                        .WithMany("Novedades")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.LoteFaenado", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.RegistroFaenamiento", b =>
                {
                    b.Navigation("Cuyes");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Productoras.Models.Lote", b =>
                {
                    b.Navigation("CodigoQR");

                    b.Navigation("Cuyes");

                    b.Navigation("Faenamientos");

                    b.Navigation("Movilizacion");

                    b.Navigation("Novedades");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Productoras.Models.Productora", b =>
                {
                    b.Navigation("Lotes");
                });
#pragma warning restore 612, 618
        }
    }
}
