// <auto-generated />
using System;
using CoopagcuyApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoopagcuyApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoopagcuyApi.Common.Auth.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.Despacho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadUnidades")
                        .HasColumnType("integer");

                    b.Property<string>("ClienteDestino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FechaDespacho")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Transporte")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Despachos");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.Faenamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoCanal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFaenamiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("OperarioResponsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PesoTotalCanalGramos")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("TemperaturaAlmacenamiento")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("UnidadesFaenadas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoteId")
                        .IsUnique();

                    b.ToTable("Faenamientos");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Productoras.Models.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadAnimales")
                        .HasColumnType("integer");

                    b.Property<string>("CentroAcopio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoLote")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("PesoTotalGramos")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ProductoraId")
                        .HasColumnType("integer");

                    b.Property<string>("ResponsableRecepcion")
                        .HasColumnType("text");

                    b.Property<bool>("SincronizadoOffline")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CodigoLote")
                        .IsUnique();

                    b.HasIndex("ProductoraId");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Productoras.Models.Productora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CatAsignado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Comunidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Productoras");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.QR.Models.CodigoQR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("BlobPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<string>("UrlPublica")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("LoteId")
                        .IsUnique();

                    b.ToTable("CodigosQR");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Recepcion.Models.Novedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoteId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PesoRegistradoGramos")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("RegistradoPor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Novedades");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.Despacho", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Faenamiento.Models.Faenamiento", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Lote", "Lote")
                        .WithOne("Faenamiento")
                        .HasForeignKey("CoopagcuyApi.Features.Faenamiento.Models.Faenamiento", "LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Productoras.Models.Lote", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Productora", "Productora")
                        .WithMany("Lotes")
                        .HasForeignKey("ProductoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Productora");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.QR.Models.CodigoQR", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Lote", "Lote")
                        .WithOne("CodigoQR")
                        .HasForeignKey("CoopagcuyApi.Features.QR.Models.CodigoQR", "LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Recepcion.Models.Novedad", b =>
                {
                    b.HasOne("CoopagcuyApi.Features.Productoras.Models.Lote", "Lote")
                        .WithMany("Novedades")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Productoras.Models.Lote", b =>
                {
                    b.Navigation("CodigoQR");

                    b.Navigation("Faenamiento");

                    b.Navigation("Novedades");
                });

            modelBuilder.Entity("CoopagcuyApi.Features.Productoras.Models.Productora", b =>
                {
                    b.Navigation("Lotes");
                });
#pragma warning restore 612, 618
        }
    }
}
